# Generated by Django 6.0.3 on 2026-04-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
