# Generated by Django 6.0.3 on 2026-04-06 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_project'),
        ('project', '0002_project_status'),
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='project.project'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='submission.submission'),
        ),
    ]
