# Generated by Django 6.0.3 on 2026-04-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedback_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='feedback_screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
