# Generated by Django 6.0.3 on 2026-04-05 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Supervisor', '0001_initial'),
        ('branchDepart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='branchDepart.branch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branchDepart.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='branchDepart.program')),
                ('students', models.ManyToManyField(limit_choices_to={'role': 'student'}, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('supervisors', models.ManyToManyField(related_name='projects', to='Supervisor.supervisorprofile')),
            ],
        ),
    ]
