"""
Django settings for pms project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # optional global templates folder
        'APP_DIRS': True,  # important! allows Django to load templates inside app folders
 
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # required for admin
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                 # Add your custom processor here:
                'Auth.context_processors.supervisor_links',
            ],
        },
    },
]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["issa-projecthub.onrender.com"]


# Application definition

INSTALLED_APPS = [
    'jazzmin', 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
   
    'Auth',
    'feedback',
  
    'branchDepart',
    
    'Audits',
    'Analytics',
    'project',
    'submission',
    'Supervisor',
    'smart_selects',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
   # 'Auth.middleware.JazzminSupervisorLinkMiddleware',
]

ROOT_URLCONF = 'pms.urls'
AUTH_USER_MODEL = "Auth.CustomUser"
LOGOUT_REDIRECT_URL = '/'



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}

WSGI_APPLICATION = 'pms.wsgi.application'
import os
import dj_database_url


DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=0,        ssl_require=True
    )
}

# ADD THIS
DATABASES['default']['CONN_HEALTH_CHECKS'] = True


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

#DATABASES = {
   # 'default': {
    #    'ENGINE': 'django.db.backends.mysql',  # switch from sqlite3 to mysql
    #    'NAME': 'pms_db',                      # your MySQL database
     #   'USER': 'issa_user',                   # MySQL user
      #  'PASSWORD': '0754206035issa',       # MySQL password
      #  'HOST': 'localhost',                   # MySQL server host
      #  'PORT': '3307',                         # MySQL port (use 3307 if MariaDB is running)
    #}
#}
  

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
JAZZMIN_SETTINGS = {
   # "show_ui_builder": True,

    "site_title": "FYPMS Admin",
    "site_header": "FYP Management",
    "site_brand": "University System",
    

    
    "layout_fixed_navbar": True,
    "layout_boxed": False,

    "icons": {
        # Apps (must be lowercase app labels)
        "project": "fas fa-project-diagram",
        "branchDepart": "fas fa-code-branch",
        "submission": "fas fa-file-upload",
        "auth": "fas fa-users-cog",
        "audits": "fas fa-clipboard-check",
        "feedback": "fas fa-comments",
        "Supervisor": "fas fa-user-tie",
        "Analytics": "fas fa-chart-line",

        # Models (optional but recommended)
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
    }
}
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
# settings.py
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True